/**
 * Placement workbench — owner only, not linked from the game.
 *
 * A real fridge, generated by the real world code and drawn by the real
 * renderer, beside the numbers that decide how big each thing is, which door it
 * may sit on and how often it appears. Drag a number, the fridge regenerates.
 * "Use in game" writes the rules to this device so the game itself generates
 * with them; "Copy JSON" hands back a blob to paste into
 * `src/game/placement.ts` when a setting is worth shipping to everyone.
 *
 * The gate is the Worker's ADMIN_KEY, checked once against /admin/api/overview
 * and then kept in localStorage, the same way the Worker's own panel does it.
 */
import { Game } from "./game/game";
import { render } from "./game/render";
import { W } from "./game/config";
import { UPGRADES, type UpgradeKey } from "./game/config";
import { obstacleArtReady } from "./game/obstacle-art";
import { gadgetArtReady } from "./game/gadget-art";
import { DEFAULT_PLACEMENT, applyPlacement, savePlacement, clearPlacement, type PlacementRules, type DoorRule } from "./game/placement";
import { setSound, setMusic } from "./game/audio";

const API = "https://magnet-climbers-api.magnetclimbers.workers.dev";
const KEY = "mc-admin-key";
const VIEW_H = 720;
const root = document.getElementById("pw")!;

const css = `
  :root { color-scheme: dark; --bg:#12151b; --panel:#1b2029; --line:#2b3340; --ink:#e8eef5; --dim:#93a1b1; --accent:#ff8a3d; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--ink); font:14px/1.45 system-ui, sans-serif; }
  .wrap { display:grid; grid-template-columns: 420px 1fr; gap:18px; padding:18px; align-items:start; }
  @media (max-width: 900px) { .wrap { grid-template-columns: 1fr; } }
  h1 { font-size:18px; margin:0 0 4px; } h2 { font-size:13px; text-transform:uppercase; letter-spacing:1px; color:var(--dim); margin:18px 0 8px; }
  .card { background:var(--panel); border:1px solid var(--line); border-radius:12px; padding:14px; }
  canvas { display:block; border-radius:10px; background:#000; width:100%; max-width:400px; }
  .stage { display:flex; gap:12px; flex-wrap:wrap; }
  label { display:block; font-size:12px; color:var(--dim); margin:10px 0 2px; }
  input[type=range] { width:100%; accent-color:var(--accent); }
  input[type=number], select, input[type=password] { width:100%; padding:7px 9px; border-radius:8px; border:1px solid var(--line); background:#0f1319; color:var(--ink); font:inherit; }
  .row { display:grid; grid-template-columns: 1fr 88px; gap:8px; align-items:center; }
  [hidden] { display:none !important; }
  button { padding:9px 14px; border-radius:9px; border:1px solid var(--line); background:#242c38; color:var(--ink); font:600 13px system-ui; cursor:pointer; }
  button.primary { background:var(--accent); color:#1a1d24; border-color:transparent; }
  .bar { display:flex; gap:8px; flex-wrap:wrap; margin-top:14px; }
  .item { border-top:1px solid var(--line); padding-top:10px; margin-top:12px; }
  .item h3 { margin:0; font-size:14px; }
  textarea { width:100%; height:150px; background:#0f1319; color:var(--ink); border:1px solid var(--line); border-radius:8px; padding:9px; font:12px/1.4 ui-monospace, monospace; }
  .fine { color:var(--dim); font-size:12px; }
  .gate { max-width:360px; margin:12vh auto; }
  .tally { font:12px ui-monospace, monospace; color:var(--dim); white-space:pre-wrap; }
`;
const style = document.createElement("style"); style.textContent = css; document.head.appendChild(style);

const esc = (s: string) => s.replace(/[<>&"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c]!));

/* ----------------------------------------------------------------- the gate */
async function keyWorks(key: string): Promise<boolean> {
  try {
    const r = await fetch(`${API}/admin/api/overview`, { headers: { Authorization: `Bearer ${key}` } });
    return r.ok;
  } catch { return false; }
}

function askForKey() {
  root.innerHTML = `<div class="card gate">
    <h1>Placement workbench</h1>
    <p class="fine">Owner only. Paste the Worker's ADMIN_KEY; it is checked against the API and then kept on this device.</p>
    <label for="k">ADMIN_KEY</label>
    <input id="k" type="password" autocomplete="off" />
    <div class="bar"><button class="primary" id="go">Unlock</button></div>
    <p class="fine" id="msg"></p>
  </div>`;
  const input = root.querySelector<HTMLInputElement>("#k")!, msg = root.querySelector<HTMLElement>("#msg")!;
  const submit = async () => {
    msg.textContent = "Checking…";
    const key = input.value.trim();
    if (await keyWorks(key)) { localStorage.setItem(KEY, key); void boot(); }
    else msg.textContent = "That key was refused, or the Worker is unreachable.";
  };
  root.querySelector("#go")!.addEventListener("click", () => void submit());
  input.addEventListener("keydown", (e) => { if (e.key === "Enter") void submit(); });
  input.focus();
}

/* ------------------------------------------------------------- the workbench */
let rules: PlacementRules = structuredClone(DEFAULT_PLACEMENT);
let seed = 4242;

/** Generate a fridge with the current rules and draw a few segments of it. */
function preview(canvases: HTMLCanvasElement[], tally: HTMLElement) {
  applyPlacement(rules);
  const levels = Object.fromEntries(UPGRADES.map((u) => [u.key, 0])) as Record<UpgradeKey, number>;
  const noop = { onPower() {}, onGameOver() {}, onCoins() {}, onGems() {} };
  const g = new Game(levels, noop, { seed, rules: "solo" });
  g.world.generateTo(60);
  g.phase = "running";
  // segments worth looking at first: the ones carrying something the rules place
  const interesting = g.world.segments.filter((s) => s.zones.some((z) => z.itemId === "plastic" || z.itemId === "ice-tray"));
  const shown = [...interesting, ...g.world.segments].slice(0, canvases.length);
  shown.forEach((s, i) => {
    g.camY = s.y - 120; g.floorY = g.camY + VIEW_H + 10; g.highestY = s.y + 200; g.time = 2;
    const ctx = canvases[i].getContext("2d")!;
    ctx.clearRect(0, 0, W, VIEW_H);
    render(ctx, g, VIEW_H, 1);
  });

  // how often each rule actually lands, over a long stretch of fridge
  const counts: Record<string, number> = { bin: 0, tray: 0, toy: 0, paper: 0 };
  for (const s of g.world.segments) for (const z of s.zones) {
    if (z.itemId === "plastic") counts.bin++;
    else if (z.itemId === "ice-tray") counts.tray++;
    else if (z.itemId?.startsWith("bumper-")) counts.toy++;
    else if (z.kind === "sticker") counts.paper++;
  }
  const segs = g.world.segments.length;
  tally.textContent = Object.entries(counts)
    .map(([k, n]) => `${k.padEnd(6)} ${String(n).padStart(4)}  ${(n / segs).toFixed(2)} per segment`)
    .join("\n") + `\n\nseed ${seed} · ${segs} segments`;
}

function controls(onChange: () => void): HTMLElement {
  const box = document.createElement("div");
  box.className = "card";
  box.innerHTML = `<h1>Placement</h1><p class="fine">Real generation, real renderer. Changes preview instantly; nothing ships until you copy the JSON into <code>src/game/placement.ts</code>.</p>`;

  for (const [key, r] of Object.entries(rules)) {
    const item = document.createElement("div");
    item.className = "item";
    const sized = typeof r.size === "object";
    item.innerHTML = `
      <h3>${esc(r.label)}</h3>
      <label>How often a segment gets one — <b data-out="rate">${r.rate.toFixed(2)}</b></label>
      <input type="range" min="0" max="1" step="0.05" value="${r.rate}" data-k="${key}" data-f="rate" />
      <div class="row">
        <div><label>Most per segment</label><input type="number" min="0" max="8" step="1" value="${r.max}" data-k="${key}" data-f="max" /></div>
        <div><label>Door</label><select data-k="${key}" data-f="door">
          ${(["either", "left", "right", "span"] as DoorRule[]).map((d) => `<option ${d === r.door ? "selected" : ""}>${d}</option>`).join("")}
        </select></div>
      </div>
      <label>Size</label>
      <select data-k="${key}" data-f="sizeMode">
        <option value="door" ${r.size === "door" ? "selected" : ""}>fill the door</option>
        <option value="auto" ${r.size === "auto" ? "selected" : ""}>fit the zone</option>
        <option value="fixed" ${sized ? "selected" : ""}>fixed</option>
      </select>
      <div class="row" data-size="${key}" ${sized ? "" : "hidden"}>
        <div><label>Width px</label><input type="number" min="8" max="400" value="${sized ? (r.size as { w: number }).w : 170}" data-k="${key}" data-f="w" /></div>
        <div><label>Height px</label><input type="number" min="8" max="720" value="${sized ? (r.size as { h: number }).h : 340}" data-k="${key}" data-f="h" /></div>
      </div>`;
    box.appendChild(item);
  }

  box.addEventListener("input", (e) => {
    const el = e.target as HTMLInputElement | HTMLSelectElement;
    const key = el.dataset.k, field = el.dataset.f;
    if (!key || !field) return;
    const r = rules[key];
    if (field === "rate") { r.rate = Number(el.value); (el.previousElementSibling!.querySelector("[data-out=rate]") as HTMLElement).textContent = r.rate.toFixed(2); }
    else if (field === "max") r.max = Number(el.value);
    else if (field === "door") r.door = el.value as DoorRule;
    else if (field === "sizeMode") {
      const row = box.querySelector<HTMLElement>(`[data-size="${key}"]`)!;
      row.hidden = el.value !== "fixed";
      r.size = el.value === "fixed"
        ? { w: Number(row.querySelector<HTMLInputElement>('[data-f="w"]')!.value), h: Number(row.querySelector<HTMLInputElement>('[data-f="h"]')!.value) }
        : (el.value as "door" | "auto");
    } else if (field === "w" || field === "h") {
      const row = box.querySelector<HTMLElement>(`[data-size="${key}"]`)!;
      r.size = { w: Number(row.querySelector<HTMLInputElement>('[data-f="w"]')!.value), h: Number(row.querySelector<HTMLInputElement>('[data-f="h"]')!.value) };
    }
    onChange();
  });
  return box;
}

async function boot() {
  await Promise.all([obstacleArtReady, gadgetArtReady]);
  setSound(false); setMusic(false);
  root.innerHTML = `<div class="wrap">
    <div id="side"></div>
    <div>
      <div class="card">
        <h2>Fridge</h2>
        <div class="stage">
          <canvas width="${W}" height="${VIEW_H}"></canvas>
          <canvas width="${W}" height="${VIEW_H}"></canvas>
          <canvas width="${W}" height="${VIEW_H}"></canvas>
        </div>
        <div class="bar">
          <button id="reseed">New fridge</button>
          <button id="use" class="primary">Use in game on this device</button>
          <button id="reset">Back to shipped defaults</button>
          <button id="copy">Copy JSON</button>
        </div>
        <h2>How often it actually lands</h2>
        <div class="tally" id="tally"></div>
        <h2>JSON</h2>
        <textarea id="json" spellcheck="false"></textarea>
        <p class="fine">Paste this into <code>DEFAULT_PLACEMENT</code> to ship it to everyone.</p>
      </div>
    </div>
  </div>`;
  const canvases = [...root.querySelectorAll("canvas")] as HTMLCanvasElement[];
  const tally = root.querySelector<HTMLElement>("#tally")!;
  const json = root.querySelector<HTMLTextAreaElement>("#json")!;
  const refresh = () => { preview(canvases, tally); json.value = JSON.stringify(rules, null, 2); };
  root.querySelector("#side")!.appendChild(controls(refresh));
  root.querySelector("#reseed")!.addEventListener("click", () => { seed = Math.floor(Math.random() * 99999); refresh(); });
  root.querySelector("#use")!.addEventListener("click", () => { savePlacement(rules); alert("Saved. New runs on this device generate with these rules."); });
  root.querySelector("#reset")!.addEventListener("click", () => { clearPlacement(); rules = structuredClone(DEFAULT_PLACEMENT); boot(); });
  root.querySelector("#copy")!.addEventListener("click", () => void navigator.clipboard.writeText(json.value));
  refresh();
}

const saved = localStorage.getItem(KEY);
if (saved) void keyWorks(saved).then((ok) => (ok ? boot() : askForKey()));
else askForKey();
